# Generated by Django 4.2.4 on 2023-08-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_name', models.CharField(max_length=100)),
                ('given', models.DateField()),
                ('back', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField()),
                ('duration_unit', models.CharField(choices=[('day', 'Day'), ('month', 'Month')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='item',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='items',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
